# Generated by Django 4.2 on 2023-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employeemodel_body_eventmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='position',
            field=models.CharField(blank=True, default='Сотрудник', max_length=123),
        ),
    ]
